version: '3.1'

services:
  db:
    image: postgres:14.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=khondominium
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432
    ports:
      - 5432:5432

  web:
    image: fabricioramosdev/khondominium/api
    container_name: fastApi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    depends_on:
      - db

volumes:
  pgdata:
    external: true